# Generated by Django 2.2.1 on 2019-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('name', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
